<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // File Storage Settings
            [
                'key' => 'file_storage_driver',
                'value' => 'local',
                'type' => 'string',
                'category' => 'file_storage',
                'group' => 'storage',
                'label' => 'Storage Driver',
                'description' => 'Choose the storage driver for file uploads (local, s3, etc.)',
                'is_public' => false,
                'is_required' => true,
                'options' => [
                    'local' => 'Local Storage',
                    's3' => 'Amazon S3',
                    'ftp' => 'FTP',
                    'sftp' => 'SFTP',
                ],
                'validation_rules' => 'required|in:local,s3,ftp,sftp',
                'sort_order' => 1,
            ],
            [
                'key' => 'file_storage_max_size',
                'value' => '10',
                'type' => 'integer',
                'category' => 'file_storage',
                'group' => 'limits',
                'label' => 'Maximum File Size (MB)',
                'description' => 'Maximum allowed file size in megabytes',
                'is_public' => false,
                'is_required' => true,
                'options' => null,
                'validation_rules' => 'required|integer|min:1|max:100',
                'sort_order' => 2,
            ],
            [
                'key' => 'file_storage_allowed_types',
                'value' => json_encode(['image', 'document', 'spreadsheet', 'archive']),
                'type' => 'array',
                'category' => 'file_storage',
                'group' => 'types',
                'label' => 'Allowed File Types',
                'description' => 'Select which file types are allowed for upload',
                'is_public' => false,
                'is_required' => true,
                'options' => [
                    'image' => 'Images (JPG, PNG, GIF, etc.)',
                    'document' => 'Documents (PDF, DOC, TXT, etc.)',
                    'spreadsheet' => 'Spreadsheets (XLS, XLSX, CSV, etc.)',
                    'archive' => 'Archives (ZIP, RAR, etc.)',
                    'video' => 'Videos (MP4, AVI, etc.)',
                    'audio' => 'Audio (MP3, WAV, etc.)',
                ],
                'validation_rules' => 'required|array',
                'sort_order' => 3,
            ],
            [
                'key' => 'file_storage_organize_by_date',
                'value' => '1',
                'type' => 'boolean',
                'category' => 'file_storage',
                'group' => 'organization',
                'label' => 'Organize Files by Date',
                'description' => 'Automatically organize uploaded files by date folders',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'boolean',
                'sort_order' => 4,
            ],
            [
                'key' => 'file_storage_keep_original_name',
                'value' => '0',
                'type' => 'boolean',
                'category' => 'file_storage',
                'group' => 'naming',
                'label' => 'Keep Original Filename',
                'description' => 'Keep original filename instead of generating unique names',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'boolean',
                'sort_order' => 5,
            ],

            // AWS S3 Settings
            [
                'key' => 'aws_s3_bucket',
                'value' => '',
                'type' => 'string',
                'category' => 'file_storage',
                'group' => 's3',
                'label' => 'S3 Bucket Name',
                'description' => 'Amazon S3 bucket name for file storage',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'required_if:file_storage_driver,s3|string',
                'sort_order' => 6,
            ],
            [
                'key' => 'aws_s3_region',
                'value' => 'us-east-1',
                'type' => 'string',
                'category' => 'file_storage',
                'group' => 's3',
                'label' => 'S3 Region',
                'description' => 'Amazon S3 region for the bucket',
                'is_public' => false,
                'is_required' => false,
                'options' => [
                    'us-east-1' => 'US East (N. Virginia)',
                    'us-east-2' => 'US East (Ohio)',
                    'us-west-1' => 'US West (N. California)',
                    'us-west-2' => 'US West (Oregon)',
                    'eu-west-1' => 'Europe (Ireland)',
                    'eu-central-1' => 'Europe (Frankfurt)',
                    'ap-south-1' => 'Asia Pacific (Mumbai)',
                    'ap-southeast-1' => 'Asia Pacific (Singapore)',
                    'ap-southeast-2' => 'Asia Pacific (Sydney)',
                    'ap-northeast-1' => 'Asia Pacific (Tokyo)',
                ],
                'validation_rules' => 'required_if:file_storage_driver,s3|string',
                'sort_order' => 7,
            ],
            [
                'key' => 'aws_s3_url',
                'value' => '',
                'type' => 'string',
                'category' => 'file_storage',
                'group' => 's3',
                'label' => 'S3 Endpoint URL',
                'description' => 'Custom S3 endpoint URL (leave empty for default AWS)',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'nullable|url',
                'sort_order' => 8,
            ],
            [
                'key' => 'aws_s3_use_path_style_endpoint',
                'value' => '0',
                'type' => 'boolean',
                'category' => 'file_storage',
                'group' => 's3',
                'label' => 'Use Path Style Endpoint',
                'description' => 'Use path-style endpoint instead of virtual-hosted-style',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'boolean',
                'sort_order' => 9,
            ],

            // File Upload Settings
            [
                'key' => 'file_upload_max_files',
                'value' => '10',
                'type' => 'integer',
                'category' => 'file_storage',
                'group' => 'upload',
                'label' => 'Maximum Files per Upload',
                'description' => 'Maximum number of files that can be uploaded at once',
                'is_public' => false,
                'is_required' => true,
                'options' => null,
                'validation_rules' => 'required|integer|min:1|max:50',
                'sort_order' => 10,
            ],
            [
                'key' => 'file_upload_auto_resize_images',
                'value' => '1',
                'type' => 'boolean',
                'category' => 'file_storage',
                'group' => 'upload',
                'label' => 'Auto Resize Images',
                'description' => 'Automatically resize large images to save storage space',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'boolean',
                'sort_order' => 11,
            ],
            [
                'key' => 'file_upload_image_max_width',
                'value' => '1920',
                'type' => 'integer',
                'category' => 'file_storage',
                'group' => 'upload',
                'label' => 'Maximum Image Width',
                'description' => 'Maximum width for uploaded images (pixels)',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'integer|min:100|max:4000',
                'sort_order' => 12,
            ],
            [
                'key' => 'file_upload_image_max_height',
                'value' => '1080',
                'type' => 'integer',
                'category' => 'file_storage',
                'group' => 'upload',
                'label' => 'Maximum Image Height',
                'description' => 'Maximum height for uploaded images (pixels)',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'integer|min:100|max:4000',
                'sort_order' => 13,
            ],
            [
                'key' => 'file_upload_image_quality',
                'value' => '85',
                'type' => 'integer',
                'category' => 'file_storage',
                'group' => 'upload',
                'label' => 'Image Quality',
                'description' => 'JPEG quality for resized images (1-100)',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'integer|min:1|max:100',
                'sort_order' => 14,
            ],

            // Security Settings
            [
                'key' => 'file_storage_scan_virus',
                'value' => '0',
                'type' => 'boolean',
                'category' => 'file_storage',
                'group' => 'security',
                'label' => 'Virus Scan Files',
                'description' => 'Scan uploaded files for viruses (requires antivirus software)',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'boolean',
                'sort_order' => 15,
            ],
            [
                'key' => 'file_storage_block_executable',
                'value' => '1',
                'type' => 'boolean',
                'category' => 'file_storage',
                'group' => 'security',
                'label' => 'Block Executable Files',
                'description' => 'Block upload of executable files (.exe, .bat, .sh, etc.)',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'boolean',
                'sort_order' => 16,
            ],
            [
                'key' => 'file_storage_require_authentication',
                'value' => '1',
                'type' => 'boolean',
                'category' => 'file_storage',
                'group' => 'security',
                'label' => 'Require Authentication',
                'description' => 'Require user authentication for file uploads',
                'is_public' => false,
                'is_required' => false,
                'options' => null,
                'validation_rules' => 'boolean',
                'sort_order' => 17,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
