version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gletr-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - gletr-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: gletr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - gletr-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: gletr-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gletr_marketplace
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: gletr_user
      MYSQL_PASSWORD: gletr_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - gletr-network

  redis:
    image: redis:7-alpine
    container_name: gletr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - gletr-network

  mailhog:
    image: mailhog/mailhog
    container_name: gletr-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - gletr-network

  minio:
    image: minio/minio
    container_name: gletr-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - gletr-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  gletr-network:
    driver: bridge
